# Generated by Django 5.1.4 on 2025-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refreshtoken',
            old_name='exp_date',
            new_name='exp',
        ),
    ]
